import type { CategoryMeta } from '../../src/types';

export interface CategoryDef extends CategoryMeta {
  /** 検証: 最低エントリ数(上流異常の検知) */
  minCount: number;
}

export const CATEGORIES: CategoryDef[] = [
  {
    id: 'soccer-m',
    sport: 'サッカー',
    category: '男子',
    entity: 'country',
    source: 'FIFAランキング',
    sourceUrl: 'https://inside.fifa.com/fifa-world-ranking/men',
    license: '最新値は Wikipedia (CC BY-SA 4.0) より取得',
    minCount: 150,
  },
  {
    id: 'soccer-w',
    sport: 'サッカー',
    category: '女子',
    entity: 'country',
    source: 'FIFA女子ランキング',
    sourceUrl: 'https://inside.fifa.com/fifa-world-ranking/women',
    license: '最新値は Wikipedia (CC BY-SA 4.0) より取得',
    minCount: 120,
  },
  {
    id: 'baseball-m',
    sport: '野球',
    category: '男子',
    entity: 'country',
    source: 'WBSC世界ランキング',
    sourceUrl: 'https://www.wbsc.org/en/rankings/baseball/men',
    minCount: 40,
  },
  {
    id: 'baseball-w',
    sport: '野球',
    category: '女子',
    entity: 'country',
    source: 'WBSC世界ランキング',
    sourceUrl: 'https://www.wbsc.org/en/rankings/baseball/women',
    minCount: 10,
  },
  {
    id: 'softball-w',
    sport: 'ソフトボール',
    category: '女子',
    entity: 'country',
    source: 'WBSC世界ランキング',
    sourceUrl: 'https://www.wbsc.org/en/rankings/softball/women',
    minCount: 10,
  },
  {
    id: 'volleyball-m',
    sport: 'バレーボール',
    category: '男子',
    entity: 'country',
    source: 'FIVB世界ランキング',
    sourceUrl: 'https://en.volleyballworld.com/volleyball/world-ranking/men',
    minCount: 30,
  },
  {
    id: 'volleyball-w',
    sport: 'バレーボール',
    category: '女子',
    entity: 'country',
    source: 'FIVB世界ランキング',
    sourceUrl: 'https://en.volleyballworld.com/volleyball/world-ranking/women',
    minCount: 30,
  },
  {
    id: 'basketball-m',
    sport: 'バスケットボール',
    category: '男子',
    entity: 'country',
    source: 'FIBA世界ランキング',
    sourceUrl: 'https://www.fiba.basketball/en/ranking/men',
    minCount: 100,
  },
  {
    id: 'basketball-w',
    sport: 'バスケットボール',
    category: '女子',
    entity: 'country',
    source: 'FIBA世界ランキング',
    sourceUrl: 'https://www.fiba.basketball/en/ranking/women',
    minCount: 60,
  },
  {
    id: 'rugby-m',
    sport: 'ラグビー',
    category: '男子',
    entity: 'country',
    source: 'World Rugbyランキング',
    sourceUrl: 'https://www.worldrugby.org/rankings/mru',
    minCount: 80,
  },
  {
    id: 'rugby-w',
    sport: 'ラグビー',
    category: '女子',
    entity: 'country',
    source: 'World Rugbyランキング',
    sourceUrl: 'https://www.worldrugby.org/rankings/wru',
    minCount: 30,
  },
  {
    id: 'hockey-m',
    sport: 'ホッケー',
    category: '男子',
    entity: 'country',
    source: 'FIH世界ランキング',
    sourceUrl: 'https://www.fih.hockey/outdoor-hockey-rankings',
    minCount: 60,
  },
  {
    id: 'hockey-w',
    sport: 'ホッケー',
    category: '女子',
    entity: 'country',
    source: 'FIH世界ランキング',
    sourceUrl: 'https://www.fih.hockey/outdoor-hockey-rankings',
    license: 'Wikipedia (CC BY-SA 4.0) より取得',
    minCount: 30,
  },
  {
    id: 'tennis-wta',
    sport: 'テニス',
    category: '女子シングルス(個人)',
    entity: 'player',
    source: 'WTAランキング',
    sourceUrl: 'https://www.wtatennis.com/rankings/singles',
    minCount: 80,
  },
];
