/**
 * IOC系3文字コード → 英語名・日本語名・国旗絵文字のマスタ。
 * 連盟によりコード体系が微妙に異なるため(FIFA: IRN / FIVB: IRI など)、
 * 同一国に複数コードがある場合は両方登録する。
 */
export interface CountryInfo {
  en: string;
  ja: string;
  flag?: string;
}

export const COUNTRIES: Record<string, CountryInfo> = {
  // アジア
  JPN: { en: 'Japan', ja: '日本', flag: '🇯🇵' },
  KOR: { en: 'South Korea', ja: '韓国', flag: '🇰🇷' },
  PRK: { en: 'North Korea', ja: '北朝鮮', flag: '🇰🇵' },
  CHN: { en: 'China', ja: '中国', flag: '🇨🇳' },
  TPE: { en: 'Chinese Taipei', ja: 'チャイニーズ・タイペイ', flag: '🇹🇼' },
  HKG: { en: 'Hong Kong', ja: '香港', flag: '🇭🇰' },
  MAC: { en: 'Macau', ja: 'マカオ', flag: '🇲🇴' },
  MNG: { en: 'Mongolia', ja: 'モンゴル', flag: '🇲🇳' },
  IRN: { en: 'Iran', ja: 'イラン', flag: '🇮🇷' },
  IRI: { en: 'Iran', ja: 'イラン', flag: '🇮🇷' },
  IRQ: { en: 'Iraq', ja: 'イラク', flag: '🇮🇶' },
  KSA: { en: 'Saudi Arabia', ja: 'サウジアラビア', flag: '🇸🇦' },
  UAE: { en: 'United Arab Emirates', ja: 'UAE', flag: '🇦🇪' },
  QAT: { en: 'Qatar', ja: 'カタール', flag: '🇶🇦' },
  KUW: { en: 'Kuwait', ja: 'クウェート', flag: '🇰🇼' },
  BRN: { en: 'Bahrain', ja: 'バーレーン', flag: '🇧🇭' },
  OMA: { en: 'Oman', ja: 'オマーン', flag: '🇴🇲' },
  YEM: { en: 'Yemen', ja: 'イエメン', flag: '🇾🇪' },
  JOR: { en: 'Jordan', ja: 'ヨルダン', flag: '🇯🇴' },
  SYR: { en: 'Syria', ja: 'シリア', flag: '🇸🇾' },
  LBN: { en: 'Lebanon', ja: 'レバノン', flag: '🇱🇧' },
  PLE: { en: 'Palestine', ja: 'パレスチナ', flag: '🇵🇸' },
  ISR: { en: 'Israel', ja: 'イスラエル', flag: '🇮🇱' },
  IND: { en: 'India', ja: 'インド', flag: '🇮🇳' },
  PAK: { en: 'Pakistan', ja: 'パキスタン', flag: '🇵🇰' },
  BAN: { en: 'Bangladesh', ja: 'バングラデシュ', flag: '🇧🇩' },
  SRI: { en: 'Sri Lanka', ja: 'スリランカ', flag: '🇱🇰' },
  NEP: { en: 'Nepal', ja: 'ネパール', flag: '🇳🇵' },
  AFG: { en: 'Afghanistan', ja: 'アフガニスタン', flag: '🇦🇫' },
  UZB: { en: 'Uzbekistan', ja: 'ウズベキスタン', flag: '🇺🇿' },
  KAZ: { en: 'Kazakhstan', ja: 'カザフスタン', flag: '🇰🇿' },
  KGZ: { en: 'Kyrgyzstan', ja: 'キルギス', flag: '🇰🇬' },
  TJK: { en: 'Tajikistan', ja: 'タジキスタン', flag: '🇹🇯' },
  TKM: { en: 'Turkmenistan', ja: 'トルクメニスタン', flag: '🇹🇲' },
  THA: { en: 'Thailand', ja: 'タイ', flag: '🇹🇭' },
  VIE: { en: 'Vietnam', ja: 'ベトナム', flag: '🇻🇳' },
  MAS: { en: 'Malaysia', ja: 'マレーシア', flag: '🇲🇾' },
  SGP: { en: 'Singapore', ja: 'シンガポール', flag: '🇸🇬' },
  SIN: { en: 'Singapore', ja: 'シンガポール', flag: '🇸🇬' },
  INA: { en: 'Indonesia', ja: 'インドネシア', flag: '🇮🇩' },
  IDN: { en: 'Indonesia', ja: 'インドネシア', flag: '🇮🇩' },
  PHI: { en: 'Philippines', ja: 'フィリピン', flag: '🇵🇭' },
  MYA: { en: 'Myanmar', ja: 'ミャンマー', flag: '🇲🇲' },
  CAM: { en: 'Cambodia', ja: 'カンボジア', flag: '🇰🇭' },
  LAO: { en: 'Laos', ja: 'ラオス', flag: '🇱🇦' },
  BRU: { en: 'Brunei', ja: 'ブルネイ', flag: '🇧🇳' },
  // ヨーロッパ
  ENG: { en: 'England', ja: 'イングランド', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  SCO: { en: 'Scotland', ja: 'スコットランド', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  WAL: { en: 'Wales', ja: 'ウェールズ', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  NIR: { en: 'Northern Ireland', ja: '北アイルランド', flag: '🇬🇧' },
  GBR: { en: 'Great Britain', ja: 'イギリス', flag: '🇬🇧' },
  IRL: { en: 'Ireland', ja: 'アイルランド', flag: '🇮🇪' },
  IRE: { en: 'Ireland', ja: 'アイルランド', flag: '🇮🇪' },
  FRA: { en: 'France', ja: 'フランス', flag: '🇫🇷' },
  GER: { en: 'Germany', ja: 'ドイツ', flag: '🇩🇪' },
  ITA: { en: 'Italy', ja: 'イタリア', flag: '🇮🇹' },
  ESP: { en: 'Spain', ja: 'スペイン', flag: '🇪🇸' },
  POR: { en: 'Portugal', ja: 'ポルトガル', flag: '🇵🇹' },
  NED: { en: 'Netherlands', ja: 'オランダ', flag: '🇳🇱' },
  BEL: { en: 'Belgium', ja: 'ベルギー', flag: '🇧🇪' },
  LUX: { en: 'Luxembourg', ja: 'ルクセンブルク', flag: '🇱🇺' },
  SUI: { en: 'Switzerland', ja: 'スイス', flag: '🇨🇭' },
  AUT: { en: 'Austria', ja: 'オーストリア', flag: '🇦🇹' },
  DEN: { en: 'Denmark', ja: 'デンマーク', flag: '🇩🇰' },
  SWE: { en: 'Sweden', ja: 'スウェーデン', flag: '🇸🇪' },
  NOR: { en: 'Norway', ja: 'ノルウェー', flag: '🇳🇴' },
  FIN: { en: 'Finland', ja: 'フィンランド', flag: '🇫🇮' },
  ISL: { en: 'Iceland', ja: 'アイスランド', flag: '🇮🇸' },
  POL: { en: 'Poland', ja: 'ポーランド', flag: '🇵🇱' },
  CZE: { en: 'Czechia', ja: 'チェコ', flag: '🇨🇿' },
  SVK: { en: 'Slovakia', ja: 'スロバキア', flag: '🇸🇰' },
  HUN: { en: 'Hungary', ja: 'ハンガリー', flag: '🇭🇺' },
  ROU: { en: 'Romania', ja: 'ルーマニア', flag: '🇷🇴' },
  BUL: { en: 'Bulgaria', ja: 'ブルガリア', flag: '🇧🇬' },
  GRE: { en: 'Greece', ja: 'ギリシャ', flag: '🇬🇷' },
  CRO: { en: 'Croatia', ja: 'クロアチア', flag: '🇭🇷' },
  SRB: { en: 'Serbia', ja: 'セルビア', flag: '🇷🇸' },
  SLO: { en: 'Slovenia', ja: 'スロベニア', flag: '🇸🇮' },
  SVN: { en: 'Slovenia', ja: 'スロベニア', flag: '🇸🇮' },
  BIH: { en: 'Bosnia and Herzegovina', ja: 'ボスニア・ヘルツェゴビナ', flag: '🇧🇦' },
  MNE: { en: 'Montenegro', ja: 'モンテネグロ', flag: '🇲🇪' },
  MKD: { en: 'North Macedonia', ja: '北マケドニア', flag: '🇲🇰' },
  ALB: { en: 'Albania', ja: 'アルバニア', flag: '🇦🇱' },
  KOS: { en: 'Kosovo', ja: 'コソボ', flag: '🇽🇰' },
  UKR: { en: 'Ukraine', ja: 'ウクライナ', flag: '🇺🇦' },
  RUS: { en: 'Russia', ja: 'ロシア', flag: '🇷🇺' },
  BLR: { en: 'Belarus', ja: 'ベラルーシ', flag: '🇧🇾' },
  MDA: { en: 'Moldova', ja: 'モルドバ', flag: '🇲🇩' },
  EST: { en: 'Estonia', ja: 'エストニア', flag: '🇪🇪' },
  LVA: { en: 'Latvia', ja: 'ラトビア', flag: '🇱🇻' },
  LAT: { en: 'Latvia', ja: 'ラトビア', flag: '🇱🇻' },
  LTU: { en: 'Lithuania', ja: 'リトアニア', flag: '🇱🇹' },
  GEO: { en: 'Georgia', ja: 'ジョージア', flag: '🇬🇪' },
  ARM: { en: 'Armenia', ja: 'アルメニア', flag: '🇦🇲' },
  AZE: { en: 'Azerbaijan', ja: 'アゼルバイジャン', flag: '🇦🇿' },
  TUR: { en: 'Türkiye', ja: 'トルコ', flag: '🇹🇷' },
  CYP: { en: 'Cyprus', ja: 'キプロス', flag: '🇨🇾' },
  MLT: { en: 'Malta', ja: 'マルタ', flag: '🇲🇹' },
  AND: { en: 'Andorra', ja: 'アンドラ', flag: '🇦🇩' },
  SMR: { en: 'San Marino', ja: 'サンマリノ', flag: '🇸🇲' },
  LIE: { en: 'Liechtenstein', ja: 'リヒテンシュタイン', flag: '🇱🇮' },
  FRO: { en: 'Faroe Islands', ja: 'フェロー諸島', flag: '🇫🇴' },
  GIB: { en: 'Gibraltar', ja: 'ジブラルタル', flag: '🇬🇮' },
  // 北中米カリブ
  USA: { en: 'USA', ja: 'アメリカ', flag: '🇺🇸' },
  CAN: { en: 'Canada', ja: 'カナダ', flag: '🇨🇦' },
  MEX: { en: 'Mexico', ja: 'メキシコ', flag: '🇲🇽' },
  CUB: { en: 'Cuba', ja: 'キューバ', flag: '🇨🇺' },
  DOM: { en: 'Dominican Republic', ja: 'ドミニカ共和国', flag: '🇩🇴' },
  PUR: { en: 'Puerto Rico', ja: 'プエルトリコ', flag: '🇵🇷' },
  JAM: { en: 'Jamaica', ja: 'ジャマイカ', flag: '🇯🇲' },
  HAI: { en: 'Haiti', ja: 'ハイチ', flag: '🇭🇹' },
  TRI: { en: 'Trinidad and Tobago', ja: 'トリニダード・トバゴ', flag: '🇹🇹' },
  CRC: { en: 'Costa Rica', ja: 'コスタリカ', flag: '🇨🇷' },
  PAN: { en: 'Panama', ja: 'パナマ', flag: '🇵🇦' },
  NCA: { en: 'Nicaragua', ja: 'ニカラグア', flag: '🇳🇮' },
  HON: { en: 'Honduras', ja: 'ホンジュラス', flag: '🇭🇳' },
  GUA: { en: 'Guatemala', ja: 'グアテマラ', flag: '🇬🇹' },
  SLV: { en: 'El Salvador', ja: 'エルサルバドル', flag: '🇸🇻' },
  ESA: { en: 'El Salvador', ja: 'エルサルバドル', flag: '🇸🇻' },
  BLZ: { en: 'Belize', ja: 'ベリーズ', flag: '🇧🇿' },
  BAH: { en: 'Bahamas', ja: 'バハマ', flag: '🇧🇸' },
  BRB: { en: 'Barbados', ja: 'バルバドス', flag: '🇧🇧' },
  BAR: { en: 'Barbados', ja: 'バルバドス', flag: '🇧🇧' },
  CUW: { en: 'Curaçao', ja: 'キュラソー', flag: '🇨🇼' },
  ARU: { en: 'Aruba', ja: 'アルバ', flag: '🇦🇼' },
  SKN: { en: 'St Kitts and Nevis', ja: 'セントクリストファー・ネイビス', flag: '🇰🇳' },
  LCA: { en: 'St Lucia', ja: 'セントルシア', flag: '🇱🇨' },
  VIN: { en: 'St Vincent and the Grenadines', ja: 'セントビンセント・グレナディーン', flag: '🇻🇨' },
  GRN: { en: 'Grenada', ja: 'グレナダ', flag: '🇬🇩' },
  ANT: { en: 'Antigua and Barbuda', ja: 'アンティグア・バーブーダ', flag: '🇦🇬' },
  ATG: { en: 'Antigua and Barbuda', ja: 'アンティグア・バーブーダ', flag: '🇦🇬' },
  AHO: { en: 'Netherlands Antilles', ja: 'オランダ領アンティル', flag: '🇧🇶' },
  BER: { en: 'Bermuda', ja: 'バミューダ', flag: '🇧🇲' },
  GUY: { en: 'Guyana', ja: 'ガイアナ', flag: '🇬🇾' },
  SUR: { en: 'Suriname', ja: 'スリナム', flag: '🇸🇷' },
  // 南米
  BRA: { en: 'Brazil', ja: 'ブラジル', flag: '🇧🇷' },
  ARG: { en: 'Argentina', ja: 'アルゼンチン', flag: '🇦🇷' },
  URU: { en: 'Uruguay', ja: 'ウルグアイ', flag: '🇺🇾' },
  PAR: { en: 'Paraguay', ja: 'パラグアイ', flag: '🇵🇾' },
  CHI: { en: 'Chile', ja: 'チリ', flag: '🇨🇱' },
  COL: { en: 'Colombia', ja: 'コロンビア', flag: '🇨🇴' },
  ECU: { en: 'Ecuador', ja: 'エクアドル', flag: '🇪🇨' },
  PER: { en: 'Peru', ja: 'ペルー', flag: '🇵🇪' },
  VEN: { en: 'Venezuela', ja: 'ベネズエラ', flag: '🇻🇪' },
  BOL: { en: 'Bolivia', ja: 'ボリビア', flag: '🇧🇴' },
  // アフリカ
  MAR: { en: 'Morocco', ja: 'モロッコ', flag: '🇲🇦' },
  ALG: { en: 'Algeria', ja: 'アルジェリア', flag: '🇩🇿' },
  TUN: { en: 'Tunisia', ja: 'チュニジア', flag: '🇹🇳' },
  EGY: { en: 'Egypt', ja: 'エジプト', flag: '🇪🇬' },
  LBY: { en: 'Libya', ja: 'リビア', flag: '🇱🇾' },
  SEN: { en: 'Senegal', ja: 'セネガル', flag: '🇸🇳' },
  CIV: { en: "Côte d'Ivoire", ja: 'コートジボワール', flag: '🇨🇮' },
  NGA: { en: 'Nigeria', ja: 'ナイジェリア', flag: '🇳🇬' },
  NIG: { en: 'Niger', ja: 'ニジェール', flag: '🇳🇪' },
  GHA: { en: 'Ghana', ja: 'ガーナ', flag: '🇬🇭' },
  CMR: { en: 'Cameroon', ja: 'カメルーン', flag: '🇨🇲' },
  COD: { en: 'DR Congo', ja: 'コンゴ民主共和国', flag: '🇨🇩' },
  CGO: { en: 'Congo', ja: 'コンゴ共和国', flag: '🇨🇬' },
  MLI: { en: 'Mali', ja: 'マリ', flag: '🇲🇱' },
  BFA: { en: 'Burkina Faso', ja: 'ブルキナファソ', flag: '🇧🇫' },
  GUI: { en: 'Guinea', ja: 'ギニア', flag: '🇬🇳' },
  GAM: { en: 'Gambia', ja: 'ガンビア', flag: '🇬🇲' },
  GAB: { en: 'Gabon', ja: 'ガボン', flag: '🇬🇦' },
  BEN: { en: 'Benin', ja: 'ベナン', flag: '🇧🇯' },
  TOG: { en: 'Togo', ja: 'トーゴ', flag: '🇹🇬' },
  RSA: { en: 'South Africa', ja: '南アフリカ', flag: '🇿🇦' },
  ZAF: { en: 'South Africa', ja: '南アフリカ', flag: '🇿🇦' },
  ZIM: { en: 'Zimbabwe', ja: 'ジンバブエ', flag: '🇿🇼' },
  ZAM: { en: 'Zambia', ja: 'ザンビア', flag: '🇿🇲' },
  KEN: { en: 'Kenya', ja: 'ケニア', flag: '🇰🇪' },
  UGA: { en: 'Uganda', ja: 'ウガンダ', flag: '🇺🇬' },
  TAN: { en: 'Tanzania', ja: 'タンザニア', flag: '🇹🇿' },
  ETH: { en: 'Ethiopia', ja: 'エチオピア', flag: '🇪🇹' },
  SUD: { en: 'Sudan', ja: 'スーダン', flag: '🇸🇩' },
  ANG: { en: 'Angola', ja: 'アンゴラ', flag: '🇦🇴' },
  MOZ: { en: 'Mozambique', ja: 'モザンビーク', flag: '🇲🇿' },
  NAM: { en: 'Namibia', ja: 'ナミビア', flag: '🇳🇦' },
  BOT: { en: 'Botswana', ja: 'ボツワナ', flag: '🇧🇼' },
  MAD: { en: 'Madagascar', ja: 'マダガスカル', flag: '🇲🇬' },
  MAW: { en: 'Malawi', ja: 'マラウイ', flag: '🇲🇼' },
  SWZ: { en: 'Eswatini', ja: 'エスワティニ', flag: '🇸🇿' },
  MRI: { en: 'Mauritius', ja: 'モーリシャス', flag: '🇲🇺' },
  RWA: { en: 'Rwanda', ja: 'ルワンダ', flag: '🇷🇼' },
  BDI: { en: 'Burundi', ja: 'ブルンジ', flag: '🇧🇮' },
  CPV: { en: 'Cabo Verde', ja: 'カーボベルデ', flag: '🇨🇻' },
  MTN: { en: 'Mauritania', ja: 'モーリタニア', flag: '🇲🇷' },
  // オセアニア
  AUS: { en: 'Australia', ja: 'オーストラリア', flag: '🇦🇺' },
  NZL: { en: 'New Zealand', ja: 'ニュージーランド', flag: '🇳🇿' },
  FIJ: { en: 'Fiji', ja: 'フィジー', flag: '🇫🇯' },
  SAM: { en: 'Samoa', ja: 'サモア', flag: '🇼🇸' },
  TGA: { en: 'Tonga', ja: 'トンガ', flag: '🇹🇴' },
  PNG: { en: 'Papua New Guinea', ja: 'パプアニューギニア', flag: '🇵🇬' },
  SOL: { en: 'Solomon Islands', ja: 'ソロモン諸島', flag: '🇸🇧' },
  VAN: { en: 'Vanuatu', ja: 'バヌアツ', flag: '🇻🇺' },
  TAH: { en: 'Tahiti', ja: 'タヒチ', flag: '🇵🇫' },
  NCL: { en: 'New Caledonia', ja: 'ニューカレドニア', flag: '🇳🇨' },
  COK: { en: 'Cook Islands', ja: 'クック諸島', flag: '🇨🇰' },
  // ---- 連盟によるコード表記ゆれ(同一国の別コード) ----
  BHR: { en: 'Bahrain', ja: 'バーレーン', flag: '🇧🇭' },
  BUR: { en: 'Burkina Faso', ja: 'ブルキナファソ', flag: '🇧🇫' },
  CAL: { en: 'New Caledonia', ja: 'ニューカレドニア', flag: '🇳🇨' },
  CUR: { en: 'Curaçao', ja: 'キュラソー', flag: '🇨🇼' },
  ESW: { en: 'Eswatini', ja: 'エスワティニ', flag: '🇸🇿' },
  FAR: { en: 'Faroe Islands', ja: 'フェロー諸島', flag: '🇫🇴' },
  LBA: { en: 'Libya', ja: 'リビア', flag: '🇱🇾' },
  LIB: { en: 'Lebanon', ja: 'レバノン', flag: '🇱🇧' },
  MGL: { en: 'Mongolia', ja: 'モンゴル', flag: '🇲🇳' },
  MWI: { en: 'Malawi', ja: 'マラウイ', flag: '🇲🇼' },
  NGR: { en: 'Nigeria', ja: 'ナイジェリア', flag: '🇳🇬' },
  PYF: { en: 'Tahiti', ja: 'タヒチ', flag: '🇵🇫' },
  SDN: { en: 'Sudan', ja: 'スーダン', flag: '🇸🇩' },
  TTO: { en: 'Trinidad and Tobago', ja: 'トリニダード・トバゴ', flag: '🇹🇹' },
  GEQ: { en: 'Equatorial Guinea', ja: '赤道ギニア', flag: '🇬🇶' },
  EQG: { en: 'Equatorial Guinea', ja: '赤道ギニア', flag: '🇬🇶' },
  GNB: { en: 'Guinea-Bissau', ja: 'ギニアビサウ', flag: '🇬🇼' },
  GBS: { en: 'Guinea-Bissau', ja: 'ギニアビサウ', flag: '🇬🇼' },
  CTA: { en: 'Central African Republic', ja: '中央アフリカ', flag: '🇨🇫' },
  CAF: { en: 'Central African Republic', ja: '中央アフリカ', flag: '🇨🇫' },
  BIZ: { en: 'Belize', ja: 'ベリーズ', flag: '🇧🇿' },
  MSR: { en: 'Montserrat', ja: 'モントセラト', flag: '🇲🇸' },
  MAT: { en: 'Montserrat', ja: 'モントセラト', flag: '🇲🇸' },
  VIR: { en: 'US Virgin Islands', ja: '米領ヴァージン諸島', flag: '🇻🇮' },
  ISV: { en: 'US Virgin Islands', ja: '米領ヴァージン諸島', flag: '🇻🇮' },
  VGB: { en: 'British Virgin Islands', ja: '英領ヴァージン諸島', flag: '🇻🇬' },
  IVB: { en: 'British Virgin Islands', ja: '英領ヴァージン諸島', flag: '🇻🇬' },
  // ---- 小国・地域 ----
  AIA: { en: 'Anguilla', ja: 'アンギラ', flag: '🇦🇮' },
  ASA: { en: 'American Samoa', ja: '米領サモア', flag: '🇦🇸' },
  BHU: { en: 'Bhutan', ja: 'ブータン', flag: '🇧🇹' },
  CAY: { en: 'Cayman Islands', ja: 'ケイマン諸島', flag: '🇰🇾' },
  CHA: { en: 'Chad', ja: 'チャド', flag: '🇹🇩' },
  COM: { en: 'Comoros', ja: 'コモロ', flag: '🇰🇲' },
  DJI: { en: 'Djibouti', ja: 'ジブチ', flag: '🇩🇯' },
  DMA: { en: 'Dominica', ja: 'ドミニカ国', flag: '🇩🇲' },
  ERI: { en: 'Eritrea', ja: 'エリトリア', flag: '🇪🇷' },
  FSM: { en: 'Micronesia', ja: 'ミクロネシア連邦', flag: '🇫🇲' },
  GDP: { en: 'Guadeloupe', ja: 'グアドループ', flag: '🇬🇵' },
  GGY: { en: 'Guernsey', ja: 'ガーンジー', flag: '🇬🇬' },
  GUM: { en: 'Guam', ja: 'グアム', flag: '🇬🇺' },
  LBR: { en: 'Liberia', ja: 'リベリア', flag: '🇱🇷' },
  LES: { en: 'Lesotho', ja: 'レソト', flag: '🇱🇸' },
  MDV: { en: 'Maldives', ja: 'モルディブ', flag: '🇲🇻' },
  MHL: { en: 'Marshall Islands', ja: 'マーシャル諸島', flag: '🇲🇭' },
  MNP: { en: 'Northern Mariana Islands', ja: '北マリアナ諸島', flag: '🇲🇵' },
  MON: { en: 'Monaco', ja: 'モナコ', flag: '🇲🇨' },
  NIU: { en: 'Niue', ja: 'ニウエ', flag: '🇳🇺' },
  NRU: { en: 'Nauru', ja: 'ナウル', flag: '🇳🇷' },
  PLW: { en: 'Palau', ja: 'パラオ', flag: '🇵🇼' },
  SEY: { en: 'Seychelles', ja: 'セーシェル', flag: '🇸🇨' },
  SLE: { en: 'Sierra Leone', ja: 'シエラレオネ', flag: '🇸🇱' },
  SOM: { en: 'Somalia', ja: 'ソマリア', flag: '🇸🇴' },
  SSD: { en: 'South Sudan', ja: '南スーダン', flag: '🇸🇸' },
  STP: { en: 'São Tomé and Príncipe', ja: 'サントメ・プリンシペ', flag: '🇸🇹' },
  SXM: { en: 'Sint Maarten', ja: 'シント・マールテン', flag: '🇸🇽' },
  TCA: { en: 'Turks and Caicos Islands', ja: 'タークス・カイコス諸島', flag: '🇹🇨' },
  TLS: { en: 'Timor-Leste', ja: '東ティモール', flag: '🇹🇱' },
  // ---- 歴史的な国・チーム ----
  AER: { en: 'Arabian Gulf', ja: 'アラビアンガルフ' },
  SCG: { en: 'Serbia and Montenegro', ja: 'セルビア・モンテネグロ' },
  TCH: { en: 'Czechoslovakia', ja: 'チェコスロバキア' },
  YUG: { en: 'Yugoslavia', ja: 'ユーゴスラビア' },
  ZAI: { en: 'Zaire', ja: 'ザイール', flag: '🇨🇩' },
};

/** Wikipedia等の英語名からコードを引くためのエイリアス(連盟固有の表記ゆれ) */
const NAME_ALIASES: Record<string, string> = {
  'ir iran': 'IRN',
  'korea republic': 'KOR',
  'korea dpr': 'PRK',
  'china pr': 'CHN',
  'republic of ireland': 'IRL',
  'congo dr': 'COD',
  'cape verde islands': 'CPV',
  'kyrgyz republic': 'KGZ',
  'czech republic': 'CZE',
  'united states': 'USA',
  'united states of america': 'USA',
  'great britain': 'GBR',
  'turkey': 'TUR',
  'turkiye': 'TUR',
  'south korea': 'KOR',
  'north korea': 'PRK',
  'st. kitts and nevis': 'SKN',
  'saint kitts and nevis': 'SKN',
  'saint lucia': 'LCA',
  'saint vincent and the grenadines': 'VIN',
  'ivory coast': 'CIV',
  "cote d'ivoire": 'CIV',
  'dr congo': 'COD',
  'democratic republic of the congo': 'COD',
  'bosnia-herzegovina': 'BIH',
  'trinidad & tobago': 'TRI',
  'malaysia': 'MAS',
  'netherlands antilles': 'AHO',
  'aotearoa new zealand': 'NZL',
};

const byEnName: Map<string, string> = new Map();
for (const [code, info] of Object.entries(COUNTRIES)) {
  const key = info.en.toLowerCase();
  if (!byEnName.has(key)) byEnName.set(key, code);
}

/** 英語国名 → コード。解決できない場合は undefined */
export function codeByEnName(name: string): string | undefined {
  const key = name.trim().toLowerCase();
  return byEnName.get(key) ?? NAME_ALIASES[key];
}

export function countryJa(code: string): string | undefined {
  return COUNTRIES[code]?.ja;
}

export function countryFlag(code: string): string {
  return COUNTRIES[code]?.flag ?? '';
}
